[package]
name = "rustywater"
version = "0.1.0"
authors = ["vscode"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpio = "0.4.1"
rocket = "0.5.0-rc.2"