[package]
name = "rustywater"
version = "0.1.0"
authors = ["vscode"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_gpiozero = "0.2.0"
rocket = "0.4.7"